apiVersion: apps/v1
kind: Deployment
metadata:
  name: existing-mono-inrepo-noport-noingress-autodeploy-20250902180342
  labels:
    app: existing-mono-inrepo-noport-noingress-autodeploy-20250902180342
spec:
  replicas: 1
  selector:
    matchLabels:
      app: existing-mono-inrepo-noport-noingress-autodeploy-20250902180342
  template:
    spec:
      imagePullSecrets:
      - name: ghcr-image-pull-secret
      containers:
      - name: existing-mono-inrepo-noport-noingress-autodeploy-20250902180342
        image: ghcr.io/koala-tests/existing-mono-inrepo-noport-noingress-autodeploy-20250902180342:latest
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2048Mi
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: existing-mono-inrepo-noport-noingress-autodeploy-20250902180342-container-vars
    metadata:
      labels:
        app: existing-mono-inrepo-noport-noingress-autodeploy-20250902180342
